export const deviceImages = {
  TM7: 'https://patternlib-all.prod.external.eu-tm-prod.vorwerk-digital.com/tm7-83b22c91a1a1e7fee3797168f05f9754.png',
  TM6: 'https://patternlib-all.prod.external.eu-tm-prod.vorwerk-digital.com/tm6-fff867f1cfc7f35118b8b6dfffca8339.png',
  TM5: 'https://patternlib-all.prod.external.eu-tm-prod.vorwerk-digital.com/tm5-a3a665744eb0093e9108135bf6b1baa4.png',
  TM31: 'https://patternlib-all.prod.external.eu-tm-prod.vorwerk-digital.com/tm31-d180149ce35a8c8d99d7a3bbff0f1bec.png',
  refrigerador:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  cocina:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'Thermomix Spiralizer':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/360989',
  estufa:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  congelador:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5430',
  frigorífico:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  microonda:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  'horno de microondas':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/8510',
  'Thermomix® Sensor':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/361967',
  'Spiralizer Thermomix':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/360989',
  'asador':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/6163',
  'horno asador':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/6163',
  refrigeración:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  refrigere:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  'Cortador Thermomix':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  'cubre cuchillas':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  refrigerator:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  oven: 'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  peeler:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  'Thermomix® Cutter':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  freezer:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  stove:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  barbecue:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/6163',
  'oven grill':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'blade cover':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  'oven with built in air fryer':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  'stove top':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'microwave oven':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/8510',
  four: 'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  réfrigérateur:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  congélateur:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5430',
  fourneau:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'couvre-lames éplucheur (Peeler)':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  'Découpe-Minute':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  'disque cuisson':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  'grill':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'plaque de cuisson':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  cuisinière:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'Découpe-Minute Thermomix®':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  éplucheur:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/344689',
  'Découpe-Spirale':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  'four avec fonction de friteuse à air chaud': 'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  'micro-ondes':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/8510',
  'Thermomix® Spiraliseur':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/360989',
  'disque de cuisson ':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  'râpe 6-en-1 Thermomix®':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  'four-gril':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'Grill':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'grill barbecue':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'Thermomix® râpe 4-en-1':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  'four micro-ondes':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/8510',
  'couvre-lame éplucheur':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/344689',
  'hob':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'blade cover & peeler':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/344689',
  'Thermomix Cutter':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  fridge:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  'blade cover and peeler':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/344689',
  'Thermomix® Spiralizer':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/360989',
  'cortador en espiral Thermomix®':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/360989',
  barbacoa:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/6163',
  'barbecue grill':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/6163',
  'oven broiler':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  'stovetop':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'grill or oven':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'microwave':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/8510',
  'grille du four':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',

};

export const countryMap = {
  'MX': 'México',
  'MXimg': 'https://cdn.gtranslate.net/flags/svg/countries/mx.svg',
  'US': 'United States',
  'USimg': 'https://cdn.gtranslate.net/flags/svg/countries/us.svg',
  'CA': 'Canada',
  'CAimg': 'https://cdn.gtranslate.net/flags/svg/countries/ca.svg',
  'AU': 'Australia',
  'AUimg': 'https://cdn.gtranslate.net/flags/svg/countries/au.svg',
  'UK': 'United Kingdom',
  'UKimg': 'https://cdn.gtranslate.net/flags/svg/countries/gb.svg',
  'AR': 'Argentina',
  'ARimg': 'https://cdn.gtranslate.net/flags/svg/countries/ar.svg',
  'CO': 'Colombia',
  'COimg': 'https://cdn.gtranslate.net/flags/svg/countries/co.svg',
  'AT': 'Austria',
  'ATimg': 'https://cdn.gtranslate.net/flags/svg/countries/at.svg',
  "CH": "Chile",
  "CHimg": 'https://cdn.gtranslate.net/flags/svg/countries/cl.svg',
  "EAU": "United Arab Emirates",
  "EAUimg": 'https://cdn.gtranslate.net/flags/svg/countries/ae.svg',
  "ES": "España",
  "ESimg": 'https://cdn.gtranslate.net/flags/svg/countries/es.svg',
  "GT": "Guatemala",
  "GTimg":'https://cdn.gtranslate.net/flags/svg/countries/gt.svg',
  "ID": "Indonesia",
  "IDimg":'https://cdn.gtranslate.net/flags/svg/countries/id.svg',
  "IS": "Islandia",
  "ISimg":'https://cdn.gtranslate.net/flags/svg/countries/is.svg',
  "KSA": "Kingdom of Saudi Arabia",
  "KSAimg":'https://cdn.gtranslate.net/flags/svg/countries/sa.svg',
  "MY": "Malaysia",
  "MYimg":'https://cdn.gtranslate.net/flags/svg/countries/my.svg',
  "NO": "Norway",
  "NOimg":'https://cdn.gtranslate.net/flags/svg/countries/no.svg',
  "PA": "Panamá",
  "PAimg":'https://cdn.gtranslate.net/flags/svg/countries/pa.svg',
  "PH": "Philippines",
  "PHimg":'https://cdn.gtranslate.net/flags/svg/countries/ph.svg',
  "PE": "Perú",
  "PEimg":'https://cdn.gtranslate.net/flags/svg/countries/pe.svg',
  "PY": "Paraguay",
  "PYimg":'https://cdn.gtranslate.net/flags/svg/countries/py.svg',
  "SG": "Singapore",
  "SGimg":'https://cdn.gtranslate.net/flags/svg/countries/sg.svg',
  "SE": "Sweden",
  "SEimg":'https://cdn.gtranslate.net/flags/svg/countries/se.svg',
  "CHE": "Switzerland",
  "CHEimg":'https://cdn.gtranslate.net/flags/svg/countries/ch.svg',
  "FR": "France",
  "FRimg":'https://cdn.gtranslate.net/flags/svg/countries/fr.svg',
  "BE": "Belgium",
  "BEimg":'https://cdn.gtranslate.net/flags/svg/countries/be.svg',
};