export const deviceImages = {
  TM7: 'https://patternlib-all.prod.external.eu-tm-prod.vorwerk-digital.com/tm7-83b22c91a1a1e7fee3797168f05f9754.png',
  TM6: 'https://patternlib-all.prod.external.eu-tm-prod.vorwerk-digital.com/tm6-fff867f1cfc7f35118b8b6dfffca8339.png',
  TM5: 'https://patternlib-all.prod.external.eu-tm-prod.vorwerk-digital.com/tm5-a3a665744eb0093e9108135bf6b1baa4.png',
  TM31: 'https://patternlib-all.prod.external.eu-tm-prod.vorwerk-digital.com/tm31-d180149ce35a8c8d99d7a3bbff0f1bec.png',
  refrigerador:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  cocina:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'Thermomix Spiralizer':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/360989',
  estufa:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  congelador:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5430',
  frigorífico:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  microonda:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  'horno de microondas':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/8510',
  horno: 'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  'Thermomix® Sensor':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/361967',
  'Spiralizer Thermomix':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/360989',
  'asador':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/6163',
  'horno asador':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/6163',
  refrigeración:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  refrigere:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  'Cortador Thermomix':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  'cubre cuchillas':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  refrigerator:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  oven: 'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  peeler:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  'Thermomix® Cutter':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  freezer:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  stove:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  barbecue:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/6163',
  'oven grill':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'blade cover':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  'oven with built in air fryer':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  'stove top':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'microwave oven':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/8510',
  four: 'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  réfrigérateur:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  congélateur:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5430',
  fourneau:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'couvre-lames éplucheur (Peeler)':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  'Découpe-Minute':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  'disque cuisson':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  'grill':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'plaque de cuisson':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  cuisinière:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'Découpe-Minute Thermomix®':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  éplucheur:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/344689',
  'Découpe-Spirale':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  'four avec fonction de friteuse à air chaud': 'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  'micro-ondes':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/8510',
  'Thermomix® Spiraliseur':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/360989',
  'disque de cuisson ':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/218594',
  'râpe 6-en-1 Thermomix®':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  'four-gril':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'Grill':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'grill barbecue':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'Thermomix® râpe 4-en-1':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  'four micro-ondes':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/8510',
  'couvre-lame éplucheur':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/344689',
  'hob':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'blade cover & peeler':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/344689',
  'Thermomix Cutter':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/341878',
  fridge:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5460',
  'blade cover and peeler':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/344689',
  'Thermomix® Spiralizer':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/360989',
  'cortador en espiral Thermomix®':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/360989',
  barbacoa:'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/6163',
  'barbecue grill':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/6163',
  'oven broiler':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5406',
  'stovetop':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/5428',
  'grill or oven':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',
  'microwave':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/8510',
  'grille du four':'https://assets.tmecosys.com/image/upload/t_web_rdp_device_56x56_2x/icons/utensil_icons/7463',

};

export const countryMap = {
  'MX': 'México',
  'MXimg': 'https://cdn.gtranslate.net/flags/svg/countries/mx.svg',
  'US': 'United States',
  'USimg': 'https://cdn.gtranslate.net/flags/svg/countries/us.svg',
  'CA': 'Canada',
  'CAimg': 'https://cdn.gtranslate.net/flags/svg/countries/ca.svg',
  'AU': 'Australia',
  'AUimg': 'https://cdn.gtranslate.net/flags/svg/countries/au.svg',
  'UK': 'United Kingdom',
  'UKimg': 'https://cdn.gtranslate.net/flags/svg/countries/gb.svg',
  'AR': 'Argentina',
  'ARimg': 'https://cdn.gtranslate.net/flags/svg/countries/ar.svg',
  'CO': 'Colombia',
  'COimg': 'https://cdn.gtranslate.net/flags/svg/countries/co.svg',
  'AT': 'Austria',
  'ATimg': 'https://cdn.gtranslate.net/flags/svg/countries/at.svg',
  "CH": "Chile",
  "CHimg": 'https://cdn.gtranslate.net/flags/svg/countries/cl.svg',
  "EAU": "United Arab Emirates",
  "EAUimg": 'https://cdn.gtranslate.net/flags/svg/countries/ae.svg',
  "ES": "España",
  "ESimg": 'https://cdn.gtranslate.net/flags/svg/countries/es.svg',
  "GT": "Guatemala",
  "GTimg":'https://cdn.gtranslate.net/flags/svg/countries/gt.svg',
  "ID": "Indonesia",
  "IDimg":'https://cdn.gtranslate.net/flags/svg/countries/id.svg',
  "IS": "Islandia",
  "ISimg":'https://cdn.gtranslate.net/flags/svg/countries/is.svg',
  "KSA": "Kingdom of Saudi Arabia",
  "KSAimg":'https://cdn.gtranslate.net/flags/svg/countries/sa.svg',
  "MY": "Malaysia",
  "MYimg":'https://cdn.gtranslate.net/flags/svg/countries/my.svg',
  "NO": "Norway",
  "NOimg":'https://cdn.gtranslate.net/flags/svg/countries/no.svg',
  "PA": "Panamá",
  "PAimg":'https://cdn.gtranslate.net/flags/svg/countries/pa.svg',
  "PH": "Philippines",
  "PHimg":'https://cdn.gtranslate.net/flags/svg/countries/ph.svg',
  "PE": "Perú",
  "PEimg":'https://cdn.gtranslate.net/flags/svg/countries/pe.svg',
  "PY": "Paraguay",
  "PYimg":'https://cdn.gtranslate.net/flags/svg/countries/py.svg',
  "SG": "Singapore",
  "SGimg":'https://cdn.gtranslate.net/flags/svg/countries/sg.svg',
  "SE": "Sweden",
  "SEimg":'https://cdn.gtranslate.net/flags/svg/countries/se.svg',
  "CHE": "Switzerland",
  "CHEimg":'https://cdn.gtranslate.net/flags/svg/countries/ch.svg',
  "FR": "France",
  "FRimg":'https://cdn.gtranslate.net/flags/svg/countries/fr.svg',
  "BE": "Belgium",
  "BEimg":'https://cdn.gtranslate.net/flags/svg/countries/be.svg',
};

export const IngredientCategory = {
  "Others": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1398"
  ],
  "Alcoholic beverages": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1514",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/186",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/284",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/144",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/327",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/453",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/148",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/285",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7235",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/447",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/130",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/219",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/175",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/290",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1755",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/970",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8274"
  ],
  "Fresh Vegetables & Greens": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/436",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/61",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2781",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/244",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/18",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1224",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/65",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/33",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/251",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/132",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5564",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/952",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/427",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/428",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2217",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3265",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8835",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2452",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5551",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/265",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1454",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/143",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3297",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/84",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/394",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/542",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/437",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/11",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/59",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/953",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/305",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/180",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/10",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/150",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/544",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2383",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6369",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/366",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/535",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1434",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/382",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/375",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/331",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5220",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1789",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1160",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2044",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6225",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1033",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5564",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1136",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/30",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1131",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7180",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5247",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/152",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/978",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/403",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/155",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1443",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/47",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3977",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1047",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2362",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/428",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15218",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/441",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1035",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1415",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/381",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/372",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3157",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/407",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1241",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1645",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/38",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/315",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/256",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/26",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/275",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/287",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/107",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/18",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/951",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/352",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/438",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/239",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1023",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/262",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1502",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/548",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3298",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/250",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/226",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3288",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/261744",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/674",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/565",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1232",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2834",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/310",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/35",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/429",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6557",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/259",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5278",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1141",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/427",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/32",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6105",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1554",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1289",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/344",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/434",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/94",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4645",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/320",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/73",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/385",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/435",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1458",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1112",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3259",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/43",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/65",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/405",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2175",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1130",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1168",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/597",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/138",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/165",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1601",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/426",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1134",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/282500",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/272",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/387",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1474",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1133",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1224",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/64",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1916",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3296",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/313",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/119",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3252",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/132",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2632",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3277",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2686",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1626",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/19",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2060",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3617",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1175",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/284557",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1682",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7807",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1290",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/373",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/522903",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/68"
  ],
  "Fresh Fruit": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/171",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/193",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4538",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2639",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3495",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5488",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/326",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/742",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/231",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2630",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/247",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2637",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/330",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/322",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1041",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/379",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3149",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/273",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1044",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/917",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15198",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/746",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/949",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/111",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5712",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2267",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8806",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/459",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1378",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4423",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1002",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/128",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/157",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2204",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/113",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5817",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/281",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/114",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/280",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2597",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7170",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/117",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/162",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/133",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2570",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1431",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/199",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/378",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/167",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/123"
  ],
  "Berries": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/133",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4876"
  ],
  "Meat & Poultry": [

    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8075",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/170",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/228",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/96960",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/506",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/956",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3857",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2989",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/388",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/471",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1403",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1125",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/559",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1448",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/248",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3434",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1791",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1511",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5967",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/308",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6036",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/277",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4636",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/520",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4346",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3930",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/473",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2642",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/324",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7319",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/525",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5662",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/71",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/916",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15062",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5147",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2988",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/472",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/127",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1606",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1668",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/470",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/274",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1155",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/254",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/323948",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2926",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1163",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/228",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1056",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2959",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/122",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1662",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3766",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/499",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/956",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/522",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/238",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3025",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3407",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/468",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/70",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/517",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/10351"
  ],
  "Fish and seafood": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4170",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/146",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/208",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3926",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/388",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/350",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5655",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/318",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/374",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1039",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1040",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/555",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1665",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/242",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5350",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/425",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3641",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2224",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/377",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/147",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1312",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/257",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/346"
  ],

  "Dairy & Eggs": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6536",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1958",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/89",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/620",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6552",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1966",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1424",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1173",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/49",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6618",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/98",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/74",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1128",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/448",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/63",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/16",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/206",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/312",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/341",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/224",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3625",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/533",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/398",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7515",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1423",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/634",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1189",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15274",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4750",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5532",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8537",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1413",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4253",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/217",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1976",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3677",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4489",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1116",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1428",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1964",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/203",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/74",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1157",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1079",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1564",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1565",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4811",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1414",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/89",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1991",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/276",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4442",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6304",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8549",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/292380",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1319",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/303",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/100074",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3618",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1965"
  ],
  "Sauces and dressings": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1135",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/252",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1463",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15064",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/458",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/182",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/58",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3765",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/10075",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/188",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/136",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1617",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2486",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7233",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3666",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4435",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3704",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2071",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/378350",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8096",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1117",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/53",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/389",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/936",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7649",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/233",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7516",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/57",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6893"

  ],
  "Oils & Cooking Fats": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5883",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/317",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15196",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/81",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/306",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/80",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2214",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3245",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/975",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/240",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3250",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/66",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8548"
  
  ],
  "Grains, Legumes & Rice": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/987",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/335",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15199",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/166",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/185",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1212",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2704",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2757",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/184",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5360",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/289",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2660",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1118",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/928",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1172",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/356",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/69",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3667",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/179",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1332",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/181",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1346",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2188",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2218",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/722",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2574",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15202",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5482",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1184"
  ],
  "Baking Ingredients": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1893",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/40",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/190",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/105",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1462",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1154",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/401",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1897",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/359",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/641",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8503",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2897",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5577",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/172453",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/632",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1307",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2559",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/301",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/294",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1317",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8471",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/319",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/268",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/99",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/612",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5676",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1137",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/440",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2153",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/345",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/40",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/108",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7184",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/146366",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2805",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/198",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/39",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6561",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7944",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1760",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7427",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5650",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1394",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1283",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5744",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/330901",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3539",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/351",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/197",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1402",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1610",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4770",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1058",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3989",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6051",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/943",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1018",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4012",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7502",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/412",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/288",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/105",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/645",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3657",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1462",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/229",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1954",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/998",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15200",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/15256",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/110",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5132",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2397",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/309",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/349",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3303",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1678",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2287"

  ],
  "Soups": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/478",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/487",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/393",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/235",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/116",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/205",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/477",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4634",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/121",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/489",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/486",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/29",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2998",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/488"
  ],
  "Water, juices and soda": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7311",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8695",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/46",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/462",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/9985",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2415",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1127",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/60",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/192",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/367",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1496",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1320",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/10161",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/52",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/9154",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/169",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/406",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2579",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3509"
  ],

  "Nuts, Seeds & Dried Fruits": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5728",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/101",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/450",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/155",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5674",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5524",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3344",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8747",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/455",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/92788",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/246",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5405",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/953",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/408",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/223",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2202",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/300",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1234",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/952",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/178",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5105",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5362",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/442",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/997",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2900",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/539",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/451",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/591",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1396",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5614",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/444",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/168",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4744",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1757",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1602",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2195",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/267",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/545",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/446",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/126",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5728",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/299",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2194",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/227",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/380",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1034",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/457",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/456",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1122",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/234",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/153",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/102",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/411",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1851",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2741",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3236",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5674",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/100",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1235",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1446",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/196",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/460",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4979",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/304",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/48",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/368"

  ],
  "Spices & Seasonings": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/534",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5966",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/24",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/424",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/550",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/423",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8835",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/245",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1525",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/391",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/95",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/386",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/149",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1115",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/76",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2370",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/357",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/418",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/985",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3428",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/9099",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/261",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5233",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/986",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/291",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/371",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3970",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/413",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/552",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1667",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8482",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/396",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1405",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/354",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/25",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1761",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/414",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/395",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/36",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1354",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3092",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/88",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1329",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/191",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/307",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/9568",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/553",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1926",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5948",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/211",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1432",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1366",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5433",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/104",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/87",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/806",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/163",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/125",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/417",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1892",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5864",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/423",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7527",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/44",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/982",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2478",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3465",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/416",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/962",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1167",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/161",  
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/370"

  ],
  "Pasta": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/141",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/9019",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3519",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4772",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/334",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2975",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/9710",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4466",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3570",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4093",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2043",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3662",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2784",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3673",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1660",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2271",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1427",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5076",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/296",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2037",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/106",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4685",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2982",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/369",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2860",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/404",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4480",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3832",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1952",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2641",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/98328",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7528",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/541",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2167"

  ],
  "Canned Goods": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1143",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/333",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1230",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1406",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1152",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2983",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/462",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/464",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/93258",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6618"
  ],
  "Bread & Bakery": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/363",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2640",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7637",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3425",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/137",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1164",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4609",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3796",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1119",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/292",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/732",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1165",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/118",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6287",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/93",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5751",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7637",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/564",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7242",

  ],
  "Syrups & Sweeteners": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/82",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2200",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5658",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1868",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5774",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2903",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1521",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3440"
  ],
  "Spreads & Butters": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4026",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/461",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2136",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2587",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1359",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7395",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/202"
  ],
  "Coffee & Tea": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/16665",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7698",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8740",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/96",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/881",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1344",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1417",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/653"
  ],
  "Pickles & Olives": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/432",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1054",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/212",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/120",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/67",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1053",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/376",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/410",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3254",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/409",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/236"
  ],
  "International Foods": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6160",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3404",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5075",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1468",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3325",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1559",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2470",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5900",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/28"
  ],
  "Breakfast Cereals & Granola": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1342",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4329",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/331522"
  ],
  "Cookies & Biscuits": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3306",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2427",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7071",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1646",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6308"
  ],
  "Organic, Natural & Vegetarian": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/3015",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1376",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2136",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/9650",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8604",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/7405",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2254",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1425",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5780"
  ],
  "Frozen Meals": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/37",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1505",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/72",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2484",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2883",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4731",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5525",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/6919",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/959",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/8995",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/960",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5308",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/2485",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/4818",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/325",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1323",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/1001"
  ],
  "Frozen Desserts": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/115"
  ],
  "Snacks": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5766"
  ],

  "Gluten-Free / Special Diets": [
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/91724",
    "https://assets.tmecosys.com/image/upload/t_web_ingredient_48x48/icons/ingredient_icons/5696"
  ]
}